# Generated by Django 4.2.13 on 2024-05-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
